config/routes.rb
Rails.application.routes.draw do
  mount Resque::Server, :at => "/resque"

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  devise_for :users
  get 'static_pages/about'

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/contact'

  get 'static_pages/submit_success'

  resources :theses, only: [:new, :create]
  
  get '/help',           to: 'static_pages#help'
  get '/about',          to: 'static_pages#about'
  get '/contact',        to: 'static_pages#contact'
  get '/submit_success', to: 'static_pages#submit_success'

  match '/404',          to: 'errors#file_not_found',        via: :all
  match '/422',          to: 'errors#unprocessable',         via: :all
  match '/500',          to: 'errors#internal_server_error', via: :all

  get 'ingests/collection' => 'ingests#collection'
  get 'ingests/dryrun_results', to: 'ingests#dryrun_results'
  get 'ingests/ingest_repost', to: 'ingests#ingest_repost'

  resources :ingests

  resources :collections

  resources :uploaded_file

  root 'static_pages#home'

end

app/controllers/theses_controller.rb
require 'nokogiri'
require 'nokogiri-pretty'

require 'dotenv'
require 'fileutils'

require 'activemessaging'
include ActiveMessaging::MessageSender

class ThesesController < ApplicationController
  #before_action :set_thesis, only: [:show, :edit, :update, :destroy]
  before_action :set_thesis, only: [:show]
  before_action :authenticate_user!

  # GET /theses
  # GET /theses.json
  def index
    #Dotenv.load
    @theses = Thesis.all

    @uploaded_files = UploadedFile.all
  end

  # GET /theses/1
  # GET /theses/1.json
  def show

  end

  # GET /theses/new
  def new
    owner = 'public'
    #@uploaded_file = UploadedFile.new

    @thesis = Thesis.new
    if self.current_user!=nil and self.current_user.surname!=nil and self.current_user.givenname!=nil
        @thesis.name = self.current_user.surname + ', ' + self.current_user.givenname
        @thesis.rightsholder = @thesis.name
    end

    @years        = Time.now.year.step(1960, -1)
    @thesis.date  = Time.now.year

    @degree_types = Settings.thesis.degreetype.to_hash.values
    @departments  = Settings.thesis.ldap.department.to_hash.values
    #@licences     = Settings.thesis.licencetype.to_hash.invert
    @licences     = Settings.thesis.licencetype.to_hash

    if self.current_user!=nil and self.current_user.department!=nil
      @thesis.department = self.current_user.department
    end

    if self.current_user!=nil #and self.current_user.department!=nil
      owner = current_user.login
    end

    # @uploaded_files = UploadedFile.new
    @uploaded_files = UploadedFile.where("owner='"+owner+"'")
    #if !@uploaded_files.nil?
    #  @uploaded_file = @uploaded_files.first
    #end
    #puts "@uploaded_files"

    # puts "----------@uploaded_files------------"
    # puts @uploaded_files.inspect
    # @uploaded_files.each do |file|
    #   puts "owner: "
    #   puts file.owner
    #   puts "original name: "
    #   puts file.original_name
    # end
    # puts "----------------------"
    # puts "END of @uploaded_files"

  end

  # GET /theses/1/edit
  def edit
  end

  # POST /theses
  # POST /theses.json
  def create
    submission_type    = params[:submission_type]
    default_thumbnails = Settings.thesis.thumbnails.default_icons.to_hash

    if 'upload' == submission_type
      uf = params[:uploaded_files]
      s = uf.inspect
      start_index = s.index('UploadedFile:')+'UploadedFile:'.length
      end_index   = start_index + 16

      uf_uid = s[start_index..end_index].strip
      #logger.debug "uf_uid: "
      #logger.debug uf_uid

      respond_to do |format|
        owner = 'public'
        if self.current_user!=nil
          owner = current_user.login
        end

        filepath   = Rails.root.to_s + Settings.thesis.tmpfilepath
        tmpfileurl = Settings.thesis.tmpfileurl
        if !dir_exist?(filepath)
          Dir.mkdir filepath
        end
        fulltmpfilename = File.absolute_path(uf.tempfile).to_s
        tmpfilename     = fulltmpfilename[(fulltmpfilename.rindex('/')+1)..-1].downcase
        #puts "Moving file: "
        #puts fulltmpfilename
        #puts filepath + tmpfilename
        FileUtils.copy(fulltmpfilename, filepath + tmpfilename)

        thumbnail = 'nothumbnail.png'

        if tmpfilename.end_with? 'pdf'
          thumbnail = default_thumbnails['pdf'.to_sym]
        elsif tmpfilename.end_with? 'doc'
          thumbnail = default_thumbnails['doc'.to_sym]
        elsif tmpfilename.end_with? 'docx'
          thumbnail = default_thumbnails['docx'.to_sym]
        elsif tmpfilename.end_with? 'zip'
          thumbnail = default_thumbnails['zip'.to_sym]
        elsif (tmpfilename.end_with? 'jpg') || (tmpfilename.end_with? 'jpeg') || (tmpfilename.end_with? 'png')
          logger.debug 'Generating thumbnail'
          thumbnail = tmpfilename + Settings.thesis.thumbnails.fileextension.to_s
          cmd = 'convert -resize x100 ' + filepath + tmpfilename + ' ' + filepath + thumbnail
          thumbnail = tmpfileurl + thumbnail
          system(cmd)
        else
          thumbnail = default_thumbnails['nothum'.to_sym]
        end
        # puts 'thumbnail'
        # puts thumbnail

        t = Time.new
        @uploaded_file = UploadedFile.new(uf_uid: uf_uid,
                                   uf_name: uf.original_filename,
                                   title: uf.original_filename,
                                   original_name: uf.original_filename,
                                   #tmp_name: File.absolute_path(uf.tempfile),
                                   tmp_name: filepath + tmpfilename,
                                   content_type: uf.content_type,
                                   thumbnail: thumbnail,
                                   owner: owner,
                                   main: "false",   #By default, newly uploaded file is not the main file
                                   created_at: t,
                                   updated_at: t)
        @uploaded_file.save

        @thesis = Thesis.new
        if self.current_user!=nil and self.current_user.surname!=nil and self.current_user.givenname!=nil
          @thesis.name = self.current_user.surname + ', ' + self.current_user.givenname
        end

        @years        = Time.now.year.step(1960, -1)
        @thesis.date  = Time.now.year

        @degree_types = Settings.thesis.degreetype.to_hash.values
        @departments  = Settings.thesis.ldap.department.to_hash.values
        #@licences     = Settings.thesis.licencetype.to_hash.invert
        @licences     = Settings.thesis.licencetype.to_hash

        if self.current_user!=nil and self.current_user.department!=nil
          @thesis.department = self.current_user.department
        end

        format.html {redirect_to new_theses_path}
        format.js
      end
    elsif 'submit' == submission_type # processing metadata submission
      mainfileid = params[:mainfile]
      logger.debug "Received post request: submit"
      more_supervisors = params[:more_supervisors]
      more_departments = params[:more_departments]
      more_subject_keywords = params[:more_subject_keywords]

      metadata_file_path = '/var/tmp/' + SecureRandom.uuid + '.dc'
      File.open(metadata_file_path, "w+") do |f|
        f.write(add_bioler_plate_fields(get_thesis_xml(more_supervisors, more_departments, more_subject_keywords).to_xml))
      end

      wf_client_file_path = '/var/tmp/' + SecureRandom.uuid + '.wf.client'
      wf_client_content  = get_workflow_client_thesis_xml_multi_files_from_db(metadata_file_path, mainfileid).to_xml
      File.open(wf_client_file_path, "w+") do |f|
        f.write(wf_client_content)
      end
      publish :'workflow_queue', wf_client_content, {'suppress_content_length' => true}
      #publish :'workflow_queue', get_workflow_client_thesis_xml(metadata_file_path).to_xml, {'suppress_content_length' => true}
      #publish :'workflow_queue', get_workflow_client_thesis_xml_single_file(metadata_file_path, File.absolute_path(uf.tempfile), "true", "ture", uf.content_type).to_xml, {'suppress_content_length' => true}

      @thesis = Thesis.new(thesis_params)

      if self.current_user!=nil and self.current_user.email!=nil
        ThesisMailer.submitted(self.current_user.email, get_thesis_summary(more_supervisors, more_departments, more_subject_keywords)).deliver_now
      end
      # remove file record and thumbnail if being generated
      remove_uploaded_files_from_db()
	  
      respond_to do |format|
        if @thesis.save
          logger.debug "Thesis saved successfully, redirecting..."
          format.html {
            redirect_to @thesis, notice: 'Thesis was successfully created.'
            return
          }
          format.json {
            render :show, status: :created, location: @thesis
          }
        else
          format.html { render :new }
          format.json { render json: @thesis.errors, status: :unprocessable_entity }
          return
        end
      end
    end

  end

  # PATCH/PUT /theses/1
  # PATCH/PUT /theses/1.json
  def update
    respond_to do |format|
      if @thesis.update(thesis_params)
        format.html { redirect_to @thesis, notice: 'Thesis was successfully updated.' }
        format.json { render :show, status: :ok, location: @thesis }
      else
        format.html { render :edit }
        format.json { render json: @thesis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theses/1
  # DELETE /theses/1.json
  def destroy
    @thesis.destroy
    respond_to do |format|
      format.html { redirect_to theses_url, notice: 'Thesis was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def get_thesis_xml
      creator     = thesis_params[:name]
      title       = thesis_params[:title]
      date        = thesis_params[:date]
      desc        = thesis_params[:abstract]
      degreetype  = thesis_params[:degree_type]
      contributor = thesis_params[:supervisor]
      publisher   = thesis_params[:department]
      subject     = thesis_params[:subjectkeyword]
      rights      = thesis_params[:rightsholder]
      licence     = thesis_params[:licence]

      builder = Nokogiri::XML::Builder.new do |xml|
        xml['oai_dc'].dc('xmlns:oai_dc' => 'http://www.openarchives.org/OAI/2.0/oai_dc/', 'xmlns:dc' => 'http://purl.org/dc/elements/1.1/') {
          xml['dc'].creator creator
          xml['dc'].title title
          xml['dc'].date date
          xml['dc'].description desc
          xml['dc'].type degreetype
          xml['dc'].contributor contributor
          xml['dc'].publisher publisher
          xml['dc'].subject subject
          xml['dc'].rights rights
          xml['dc'].licence licence
        }
      end
    end

    def get_thesis_xml(more_supervisors, more_departments, more_subject_keywords)
      creator     = thesis_params[:name]
      title       = thesis_params[:title]
      date        = thesis_params[:date]

app/helpers/theses_helper.rb
module ThesesHelper
end

app/views/theses/_form.html.erb
  <div class="panel panel-default" id="panel_uploaded_files">
    <div class="panel-heading"><strong>Upload Files</strong><br /><br />Drag &amp; Drop files into the box below OR click 'Choose Files' button. <br /><br />Please remove your student number from your thesis before uploading. We would strongly prefer PDF as the format for your main dissertation text and the uploader requires you to upload a PDF as the main text. See <%= link_to "Help",   help_path %> for more information.</div>

    <div class="panel-body fade" id="dropzone">
        <ul class="row" style="list-style-type: none;" id="files-list">
            <% if !@uploaded_files.nil? && @uploaded_files.length >0 %>
              <% @uploaded_files.each do |file| %>
                  <li class="col-xs-3">
                    <div class="fileview">
                        <div class="imagewrapper">
                          <%= link_to image_tag(file.thumbnail, alt: file.title, class: 'img-thumbnail', size: '100x100'),
                                    file.thumbnail, target: '_blank'%>
                        </div>
                        <div class="imagetitle">
                          <% if file.title.present? %>
                              <%=file.title %>
                          <% end %>
                        </div>

                        <div class="defaultfile">
                          <% if file.original_name.downcase.end_with? "pdf" %>
                              <% if file.main.present? and file.main=='true' %>
                                  <span title="Click the radio button to choose this file as the main text.">main</span>&nbsp;<input type="radio" name="defaultFile" id="file<%=file.id.to_s%>" value="<%=file.id.to_s%>" checked="checked">
                              <% else %>
                                  <span title="Click the radio button to choose this file as the main text.">main</span>&nbsp;<input type="radio" name="defaultFile" id="file<%=file.id.to_s%>" value="<%=file.id.to_s%>">
                              <% end %>
                          <% end %>
                        </div>

                        <div class="imagedel">

                          <span title="Click to delete this file"><%= link_to 'Delete', file, method: :delete, data: {confirm: 'Are you sure?'}, :remote => true, :class => 'delete_file', :id => 'delete'+file.id.to_s %></span>

                        </div>
                    </div>
                  </li>
              <% end %>
            <% end %>
        </ul>
      </div>
  </div>




<div class="panel panel-default">
 <div class="panel-heading">Dissertation details</div>

 <div class="panel-body">
  <%= form_for(@thesis) do |f| %>
    <div class="form-group">
      <% if @thesis.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@thesis.errors.count, "error") %> prohibited this thesis from being saved:</h2>

            <ul>
              <% @thesis.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
    </div>
    <div class="form-group">
      <!--<div class="control-label col-xs-2 form-fields">-->
      <!--List of uploaded files-->
      <!--</div>-->
      <%= image_tag("remove.gif", alt: "Delete",   title: "Delete",   size: "16x16", id: "delete_img_template", :class => "delete_img_template") %>

      <!--<div id="dropzone" class="fade">Drop files here</div><br/>-->
      <div class="progress-wrapper">
        <p>Bitrate: <span class="bitrate"></span></p>
        <div class="progress">
          <div class="progress-bar" role="progressbar">
            0%
          </div>
        </div>
      </div>

      <div class="control-label col-xs-2 form-fields">
        <%= f.label "File upload" %>
      </div>
      <div class="col-xs-10 form-fields">
        <%= f.file_field :uploaded_files, required: true, multiple: true, name: 'uploaded_files', class: "btn file_upload_button" %>
      </div>

      <div class="control-label col-xs-2 form-fields">
        <%= f.label "Author's name" %>
      </div>
      <div class="col-xs-10 form-fields">
        <%= f.text_field :name, :size=>"80", placeholder: "Surname, Forename" %>
      </div>

      <div class="control-label col-xs-2 form-fields">
        <%= f.label "Dissertation title" %><span style="color:red;font-size:14px;">*</span>
      </div>
      <div class="col-xs-10 form-fields">
        <%= f.text_field :title, :size=>"80", placeholder: "Dissertation title", class: "theses_title"  %>
      </div>

      <div class="control-label col-xs-2 form-fields">
        <%= f.label :date %>
      </div>
      <div class="col-xs-10 form-fields">
        <%= f.collection_select :date, @years, :to_s, :to_s, include_blank: false %>
      </div>
      <br/>

      <div class="control-label col-xs-2 big-form-fields">
        <%= f.label :abstract %>
      </div>
      <div class="col-xs-10 big-form-fields">
        <%= f.text_area :abstract, :size => "80x5", placeholder: "Abstract" %>
      </div>
      <br/>

      <div class="control-label col-xs-2 form-fields">
        <%= f.label "Degree type"  %>
      </div>
      <div class="col-xs-10 form-fields">
        <%= f.collection_select :degreetype, @degree_types, :to_s, :to_s, include_blank: false %>
      </div>

      <div>
          <div class="control-label col-xs-2 form-fields">
            <%= f.label "Degree supervisor" %>
          </div>

          <div class="col-xs-10 form-fields" id="divSupervisor">
            <%= f.text_field :supervisor, :size=>"80", placeholder: "Surname, Forename" %>
            <%= image_tag("add.gif",    alt: "Add another supervisor", title: "Add another supervisor", size: "16x16", id: "add_supervisor",    :class => "add_image") %>
          </div>
      </div>
      <br/>

      <div>
          <div class="control-label col-xs-2 form-fields">
            <%= f.label :department %>
          </div>
          <div class="col-xs-10 form-fields" id="divDepartment">
            <%= f.collection_select :department, @departments, :to_s, :to_s, include_blank: false %>
            <%= image_tag("add.gif", alt: "Add another department", title: "Add another department", size: "16x16", id: "add_department", class: "add_image") %>
          </div>
      </div>
      <br/>

      <div>
          <div class="control-label col-xs-2 form-fields">
            <%= f.label "Subject keyword" %>
          </div>
          <div class="col-xs-10 form-fields" id="divSubjectKeyword">
            <%= f.text_field :subjectkeyword, :size=>"80", placeholder: "Subject keyword" %>
            <%= image_tag("add.gif", alt: "Add another subject keyword", title: "Add another subject keyword", size: "16x16", id: "add_subjectkeyword", class: "add_image") %>
          </div>
          <br/>
      </div>

      <div class="control-label col-xs-2 form-fields">
        <%= f.label "Rights holder" %>
      </div>
      <div class="col-xs-10 form-fields">
        <%= f.text_field :rightsholder, :size=>"80", placeholder: "Rights holder" %>
      </div>
      <br/>

      <div class="control-label col-xs-2 form-fields">
        <%= f.label :licence %>
      </div>
      <div class="col-xs-10 medium-form-fields">
        <% first_time = true %>
        <% @licences.each do |licence| %>
            <% if first_time == true %>
                <%= radio_button_tag 'licence', licence[0], true %>
                <% first_time = false %>
            <% else %>
                <%= radio_button_tag 'licence', licence[0], false %>
            <% end %>
            <%= licence[1] %><br/>
        <% end %>
      </div>
      <div class="form-fields">
      </div>
      <div class="col-xs-offset-2 col-xs-10 form-fields">
        <span style="font-weight: bold;">* Mandatory field</span>
      </div>
      <br/>
      <br/>
      <br/>
      <br/>
      <div class="form-fields">
      </div>

      <div class="col-xs-offset-2 col-xs-10 form-fields">
        <%= f.label "Upload Dissertation", :id => 'btnSubmit', :class => 'btn btn-primary' %>
      </div>


      <br/>
    </div>

    <div id="spinner">

    </div>

  <% end %>
 </div>
</div>

app/views/theses/create.js.erb
<% if !@uploaded_file.nil? %>

    <% if @uploaded_file.new_record? %>
        alert('The file(s) could not be uploaded: <%= j @uploaded_file.errors.full_messages.join(', ').html_safe %>');
    <% else %>
        $('#panel_uploaded_files').css('display', "block");

        $('#files-list').prepend('<%= j render @uploaded_file %>');
    <% end %>

<% end %>

app/views/theses/edit.html.erb
<h1>Editing Dissertation</h1>

<%= render 'form' %>

<%= link_to 'Show', @thesis %> |
<%= link_to 'Back', theses_path %>

app/views/theses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dissertation</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Date</th>
      <th>Abstract</th>
      <th>Degreetype</th>
      <th>Supervisor</th>
      <th>Department</th>
      <th>Subjectkeyword</th>
      <th>Rightsholder</th>
      <th>Licence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @theses.each do |thesis| %>
      <tr>
        <td><%= thesis.name %></td>
        <td><%= thesis.title %></td>
        <td><%= thesis.date %></td>
        <td><%= thesis.abstract %></td>
        <td><%= thesis.degreetype %></td>
        <td><%= thesis.supervisor %></td>
        <td><%= thesis.department %></td>
        <td><%= thesis.subjectkeyword %></td>
        <td><%= thesis.rightsholder %></td>
        <td><%= thesis.licence %></td>
        <td><%= link_to 'Show', thesis %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dissertation', new_thesis_path %>

app/views/theses/new.html.erb
<br/><br/><br/>
<div style="text-align: center">
    <h3><%= image_tag("thesis.jpg", alt: "Thesis", size: "64x64") %>Dissertation upload</h3><br/>
</div>

<%= render 'form' %>

app/views/theses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @thesis.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @thesis.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @thesis.date %>
</p>

<p>
  <strong>Abstract:</strong>
  <%= @thesis.abstract %>
</p>

<p>
  <strong>Degreetype:</strong>
  <%= @thesis.degreetype %>
</p>

<p>
  <strong>Supervisor:</strong>
  <%= @thesis.supervisor %>
</p>

<p>
  <strong>Department:</strong>
  <%= @thesis.department %>
</p>

<p>
  <strong>Subjectkeyword:</strong>
  <%= @thesis.subjectkeyword %>
</p>

<p>
  <strong>Rightsholder:</strong>
  <%= @thesis.rightsholder %>
</p>

<p>
  <strong>Licence:</strong>
  <%= @thesis.licence %>
</p>

<%= link_to 'Home', "/" %>