config/routes.rb
Rails.application.routes.draw do
  mount Resque::Server, :at => "/resque"

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  devise_for :users
  get 'static_pages/about'

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/contact'

  get 'static_pages/submit_success'

  resources :theses, only: [:new, :create]
  
  get '/help',           to: 'static_pages#help'
  get '/about',          to: 'static_pages#about'
  get '/contact',        to: 'static_pages#contact'
  get '/submit_success', to: 'static_pages#submit_success'

  match '/404',          to: 'errors#file_not_found',        via: :all
  match '/422',          to: 'errors#unprocessable',         via: :all
  match '/500',          to: 'errors#internal_server_error', via: :all

  get 'ingests/collection' => 'ingests#collection'
  get 'ingests/dryrun_results', to: 'ingests#dryrun_results'
  get 'ingests/ingest_repost', to: 'ingests#ingest_repost'

  resources :ingests

  resources :collections

  resources :uploaded_file

  root 'static_pages#home'

end

app/models/ingest.rb
class Ingest < ActiveRecord::Base
end

app/controllers/ingests_controller.rb
class IngestsController < ApplicationController
  #before_action :set_ingest, only: [:show,]
  before_action :authenticate_user!

  # GET /ingests
  # GET /ingests.json
  def index
    #@ingests = Ingest.all
  end

  # GET /ingests/1
  # GET /ingests/1.json
  def show
  end

  # GET /ingests/new
  def new

    unless session[:ingest].class == NilClass
      session[:ingest].clear
    end
    @ingest = Ingest.new
    session[:failures] = {}
  end

  # GET /ingests/dryrun_results
  def dryrun_results

  end

  def ingest_repost
    @ingest = Ingest.new(session[:ingest])

    @dryrun_report = IngestRun.new.ingest(@ingest[:folder], nil, @ingest[:content], @ingest[:rights], @ingest[:filestore], @ingest[:parent], @ingest[:worktype],@ingest[:photographer], @ingest[:repository],false, self.current_user.get_ldap_email, @ingest[:metadataonly])

    respond_to do |format|
      format.html { render :dryrun_results }
    end
  end

  def collection
    #@collections_list = '<div id="html1"><ul><li id="york1234">test list!</li></ul></div>'.html_safe
    @collections_list = get_collections_tree
    render :partial => 'collections/index'
  end

  # POST /ingests
  # POST /ingests.json
  def create

    @ingest = Ingest.new(ingest_params)
    @dryrun_report = IngestRun.new.ingest(@ingest[:folder], params[:ingest][:file].tempfile, @ingest[:content], @ingest[:rights], @ingest[:filestore], @ingest[:parent], @ingest[:worktype],@ingest[:photographer], @ingest[:repository],@ingest[:dryrun], self.current_user.get_ldap_email,@ingest[:metadataonly])

    unless session[:ingest].class == NilClass
      session[:ingest].clear
    end

    #remove tmpfile to avoid massive session
    params[:ingest].delete :file
    session[:ingest] = ingest_params

    respond_to do |format|
      #if @ingest.save
      format.html { render :dryrun_results }
      #format.json { render :index, status: :created, location: @ingest }
      #else
      # format.html { render :new, notice: notice }
      #  format.json { render json: @ingest.errors, status: :unprocessable_entity }
      #end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ingest
    @ingest = Ingest.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ingest_params
    params.require(:ingest).permit(:folder, :file, :content, :rights, :worktype, :repository, :filestore, :parent, :photographer, :dryrun, :metadataonly)
  end
end

app/views/ingests/_form.html.erb
<%= form_for(@ingest) do |f| %>
    <% if @ingest.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@ingest.errors.count, "error") %> prohibited this ingest from being saved:</h2>

            <ul>
                <% @ingest.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label "Select the filestore" %>&nbsp;
        <%= f.select(:filestore) do %>
            <%= options_for_select([
                                           ['please select', ''],
                                           ['yodlprodingest'],
                                           ['archbishop']
                                   ]) %>
            <%= :id %>
        <% end %>
    </div>
    <br/>
    <div class="field ingest 1">
        <%= f.label "Path to files" %>&nbsp;
        <%= f.text_field :folder, :size => 50 %>
        <p>For example: '<i>archbishop/Folder1/Folder2/</i>' enter '<i>Folder1/Folder2</i>'.<br/>
            Leave blank for root directory.
        </p>
    </div>
    <br/>
    <div class="field ingest 1">
        <%= f.label "Select a CSV file to upload" %>&nbsp;
        <%= f.file_field :file %>
    </div>
    <br/>

    <div class="field ingest 2">
        <%= f.label "Type of Content to Ingest" %>&nbsp;
        <%= f.select(:content) do %>
            <%= options_for_select([
                                           ['please select', ''],
                                           ['Collections'],
                                           ['Theses'],
                                           ['Exam papers'],
                                           ['Scholarly texts'],
                                           ['Images'],
                                   ]) %>

            <%= :id %>

        <% end %>

    </div>
    <div class="field field-toggle-off">
        <%= f.label "Metadata Only" %>&nbsp;
        <%= f.check_box(:metadataonly, {checked: false}) %>
        <p>Indicate if the spreadsheet should be processed as metadata only.</p>
    </div>
    <br/>
    <div class="field field-toggle-off">
        <%= f.label "Imager", :class => 'field-toggle-off' %>&nbsp;
        <% if self.current_user.nil? %>
            <%= f.text_field :photographer, :size => 50 %>
        <% else %>
            <%= f.text_field :photographer, :value => self.current_user.surname + ', ' + self.current_user.givenname, :size => 50 %>
        <% end %>
    </div>
    <br/>
    <div class="field field-toggle-off">
        <%= f.label "Worktype" %>&nbsp;
        <%= f.text_field :worktype, :size => 50 %>
        <p>Leave blank if this is in the csv</p>
    </div>
    <br/>
    <div class="field ingest 3">
        <%= f.label :rights %>&nbsp;
        <% @hash = Hash.new()
           @hash = {'please select' => ''}
           @hash.reverse_merge!(Settings.rights.to_hash { |l| [l['label']] }) %>
        <%= f.select :rights, options_for_select(@hash) %>
    </div>
    <br/>
    <div class="field ingest 4">
        <%= f.label :repository %><br/>
        <%= f.select :repository, options_for_select(Settings.repository.to_hash { |l| [l['label']] }), :class => 'field-toggle-off' %>
    </div>
    <%= f.hidden_field :dryrun, :value => 'true' %>
    <br/>
    <div class="field ingest 4">
        <%= f.label "Parent Collection" %><br/>
        <%= f.label "Select Collection", :id => 'btnColl', :class => 'btn btn-primary' %>
        <p>Leave blank if this is in the csv</p>

        <div id="divColl" style="display: none;">

        </div>
        <br/>
        <br class="remove"/>
        <%= f.label "Collection pid:", :class => 'remove' %>
        <br class="remove"/>
        <%= f.text_field :parent %>
    </div>
    <div class="actions ingest 4">
        <%= f.submit "Test Ingest", class: "pretty_button" %>
    </div>
    <br/>
<% end %>

app/views/ingests/dryrun_results.html.erb
<br/><br/>
<h1>Ingest Report</h1>
<p id="notice"><%= notice %></p>
<% if self.current_user.get_department_code == 'libarch' or self.current_user.get_department_code == 'directinfo' %>

    <p>
        <%= @dryrun_report %>
    </p>

    <div class="pretty_button">
        <%= link_to 'New Ingest', new_ingest_path %>
    </div>

<% else %>

    <p>You are not authorized to view this page</p>
    <br /><br />

<% end %>

app/views/ingests/index.html.erb
<br/><br/>
<h1>Batch Ingest</h1>
<p id="notice"><%= notice %></p>
<% if self.current_user.get_department_code == 'libarch' or self.current_user.get_department_code == 'directinfo' %>

    <div class="pretty_button">
        <%= link_to 'New Ingest', new_ingest_path %>
    </div>

    <h3>York Digital Library Batch Ingest Tool</h3>
    <p>Please consult the instructions:</p>
    <p><%= link_to 'York Digital Library Batch Ingest Tool', 'https://wiki.york.ac.uk/display/dlib/York+Digital+Library+Batch+Ingest+Tool' %></p>

    <% if session[:failures] %>

        <%= render 'failures' %>
    <% end %>

<% else %>

    <p><%= self.current_user.get_department_code %> is not authorized to view this page.</p>

    <br /><br />

<% end %>

app/views/ingests/new.html.erb
<br/><br/>
<h3>New Batch Ingest</h3>
<br/>

<% if self.current_user.get_department_code == 'libarch' or self.current_user.get_department_code == 'directinfo' %>

    <%= render 'form' %>

<% else %>

    <p><%= self.current_user.get_department_code %> is not authorized to view this page.</p>

    <br /><br />

<% end %>

app/views/ingests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Folder:</strong>
    <%= @ingest.folder %>
</p>

<p>
    <strong>File:</strong>
    <%= @ingest.file %>
</p>

<%= link_to 'Edit', edit_ingest_path(@ingest) %> |
<%= link_to 'Back', ingests_path %>