config/routes.rb
Rails.application.routes.draw do
  mount Resque::Server, :at => "/resque"

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  devise_for :users
  get 'static_pages/about'

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/contact'

  get 'static_pages/submit_success'

  resources :theses, only: [:new, :create]
  
  get '/help',           to: 'static_pages#help'
  get '/about',          to: 'static_pages#about'
  get '/contact',        to: 'static_pages#contact'
  get '/submit_success', to: 'static_pages#submit_success'

  match '/404',          to: 'errors#file_not_found',        via: :all
  match '/422',          to: 'errors#unprocessable',         via: :all
  match '/500',          to: 'errors#internal_server_error', via: :all

  get 'ingests/collection' => 'ingests#collection'
  get 'ingests/dryrun_results', to: 'ingests#dryrun_results'
  get 'ingests/ingest_repost', to: 'ingests#ingest_repost'

  resources :ingests

  resources :collections

  resources :uploaded_file

  root 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer container-fixed">
  <small>
    The <a href="/">Upload System</a>
    by <a href="http://dlib.york.ac.uk/">York Digital Library</a>
  </small>
  <nav>
    <ul>

      <% if self.current_user != nil and self.current_user.get_department_code == 'libarch' %>
        <li><%= link_to "Ingests",               ingests_path %></li>
      <% end %>
      <li><%= link_to "Help",               help_path %></li>
      <li><%= link_to "Legal Statements",   'http://www.york.ac.uk/docs/disclaimer/disclaimer.htm' %></li>
      <li><%= link_to "Contact us",         contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse container-fixed">
  <div class="container-fixed" style="padding-left: 0px;">
    <%= link_to image_tag("YODL_Banner_Rev_03d.jpg", alt:"York Digital Library Dissertation upload"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right" style="padding-right: 30px;">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if user_signed_in? %>
            <!--<li><div style="color:#FFFFFF; padding-top: 15px;"><%= current_user.login %></div></li>-->
            <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
        <%else%>
            <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= yield :javascript_includes %>

  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>

    <br/><br/>
    <div class="container-fixed">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
</body>
</html>